In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
data.shape

(10000, 14)

In [5]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [6]:
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [7]:
data.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary        Exited  
count  10000.00000    10000.000000     10000.000000  10000.000000  
mean       0.70550        0.515100    100090.239881      0.203700  
std        0.45584        0.499797     57510.492818      0.402769  
min        0.00000        0.000000        11.580000      0.000000  
25%        0.00000        0.000000     51002.110000      0.000000  
50%        1.00000        1.000000    100193.915000      0.000000  
75%        1.00000        1.000000    149388.247500      0.000000  
max        1.00000        1.000000    199992.480000      1.000000

In [8]:
label_encoder=LabelEncoder()
data['Gender']=label_encoder.fit_transform(data['Gender'])

In [9]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [10]:
data['Gender'].unique()

array([0, 1])

In [11]:
data['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [12]:
## one Hot encoding  for 'Geography'
##Y lablel encoding not applied on "Geography" column ? Ans. Because it has more than 2 unique values.
## If we use label encoding, It gives the result as 0,1,2. Model understand that value 2 has more important than other values. But its wrong

In [13]:
from sklearn.preprocessing import OneHotEncoder

one_hot=OneHotEncoder()

In [14]:
one_hot_geo=one_hot.fit_transform(data[['Geography']])

In [15]:
one_hot_geo

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [16]:
one_hot.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [17]:
one_hot_geo.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [18]:
geo_df=pd.DataFrame(one_hot_geo.toarray(),columns=one_hot.get_feature_names_out())

In [19]:
geo_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [20]:
##combine one hot enocode df with original data
data=pd.concat([data.drop('Geography',axis=1),geo_df],axis=1)

In [21]:
data

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1               1.0   
1                  1        112542.58       0               0.0   
2                  0        113931.57       1               1.0   
3                  0         93826.63       0               1.0   
4                  1         79084.10       0               0.0   
...              ...              ...     ...               ...   
9995               0         96270.64       0               1.0   
9996               1        101699.77       0               1.0   
9997               1         42085.58       1               1.0   
9998               0         92888.52       1               0.0   
9999               0         38190.78       0               1.0   

      Geography_Germany  Geography_Spain  
0                   0.0              0.0  
1                   0.0              1.0  
2                   0.0              0.0  
3                   0.0              0.0  
4                   0.0              1.0  
...                 ...              ...  
9995                0.0              0.0  
9996                0.0              0.0  
9997                0.0              0.0  
9998                1.0              0.0  
9999                0.0              0.0  

[10000 rows x 13 columns]

In [22]:
## save the labelled data and onehot encoder data in pickle file

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot,file)

In [23]:
## splitting dependent and independent feature 
X=data.drop('Exited',axis=1)
Y=data['Exited']

In [24]:
X

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0                  1        101348.88               1.0                0.0   
1                  1        112542.58               0.0                0.0   
2                  0        113931.57               1.0                0.0   
3                  0         93826.63               1.0                0.0   
4                  1         79084.10               0.0                0.0   
...              ...              ...               ...                ...   
9995               0         96270.64               1.0                0.0   
9996               1        101699.77               1.0                0.0   
9997               1         42085.58               1.0                0.0   
9998               0         92888.52               0.0                1.0   
9999               0         38190.78               1.0                0.0   

      Geography_Spain  
0                 0.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 1.0  
...               ...  
9995              0.0  
9996              0.0  
9997              0.0  
9998              0.0  
9999              0.0  

[10000 rows x 12 columns]

In [25]:
Y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [26]:
## Train test split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=69)

You should always do StandardScaling after train_test_split, not before.

Why is this wrong?

Because the scaler uses the mean and standard deviation of the entire dataset, including the test data → this is called data leakage.

In [27]:
##Standardscalar

scalar=StandardScaler()

In [28]:
x_train=scalar.fit_transform(x_train)  # fit + transform only on training
x_test=scalar.transform(x_test)   # transform using training params

In [29]:
x_train

array([[ 1.196046  ,  0.9056767 , -0.65829995, ...,  0.99104014,
        -0.57273139, -0.57504086],
       [-0.17374264,  0.9056767 , -1.23120172, ...,  0.99104014,
        -0.57273139, -0.57504086],
       [-0.82750541,  0.9056767 , -0.56281632, ..., -1.00904087,
         1.74601919, -0.57504086],
       ...,
       [-0.96240883,  0.9056767 , -0.75378358, ...,  0.99104014,
        -0.57273139, -0.57504086],
       [-0.5992073 ,  0.9056767 , -0.27636543, ...,  0.99104014,
        -0.57273139, -0.57504086],
       [ 2.06772969,  0.9056767 , -0.8492672 , ...,  0.99104014,
        -0.57273139, -0.57504086]])

In [30]:
x_test

array([[ 0.64605511, -1.10414677,  0.86943812, ..., -1.00904087,
        -0.57273139,  1.73900686],
       [ 0.0234239 , -1.10414677,  3.35201248, ...,  0.99104014,
        -0.57273139, -0.57504086],
       [-0.16336546,  0.9056767 ,  1.06040538, ..., -1.00904087,
        -0.57273139,  1.73900686],
       ...,
       [ 0.82246728, -1.10414677,  0.39201998, ..., -1.00904087,
        -0.57273139,  1.73900686],
       [ 0.8120901 , -1.10414677, -0.08539817, ...,  0.99104014,
        -0.57273139, -0.57504086],
       [-1.98975032, -1.10414677,  0.29653635, ..., -1.00904087,
        -0.57273139,  1.73900686]])

In [31]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scalar,file)

1. What is fit()?
fit() = Learn / Calculate / Train

It learns the required parameters from the data, but does NOT return transformed output.

Examples:

StandardScaler.fit() → learns mean and std

CountVectorizer.fit() → learns vocabulary

PCA.fit() → learns principal components

You use fit() when you want to learn something from the dataset.
🔥 2. What is transform()?
transform() = Apply what was learned

It uses the parameters learned during fit() to transform new data.

Examples:

StandardScaler → applies the learned mean & std to scale the data

CountVectorizer → converts new text to vectors using learned vocab

PCA → projects new data onto learned components

You use transform() on:

training data (after fit)

test data

future data in production

🔥 3. What is fit_transform()?
fit_transform() = fit + transform (only on same data)

It does two things in one step:

Learns parameters from the data (fit)

Immediately applies transformation (transform)

When to use what? (Golden Rule)

✅ On training data

fit_transform()

✅ On test data

transform()    # ONLY transform, NEVER fit

❌ Never use fit() on test data


Because the test set must be like new unseen data.

| Method              | Meaning              | Learns Params | Returns Transformed Data | Use Case                       |
| ------------------- | -------------------- | ------------- | ------------------------ | ------------------------------ |
| **fit()**           | Learn/Calculate      | ✔️            | ❌                        | Only on training data          |
| **transform()**     | Apply learned params | ❌             | ✔️                       | Training (after fit) + Testing |
| **fit_transform()** | fit + transform      | ✔️            | ✔️                       | Only for training data         |
