In [1]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 51.1 MB/s eta 0:00:00


In [2]:
import gensim

In [3]:
from gensim.models import word2vec,keyedvectors

In [4]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [8]:
money = wv['Money']

In [9]:
money

array([-0.05957031,  0.18359375, -0.2578125 ,  0.02990723,  0.09667969,
        0.00389099, -0.01904297, -0.06298828,  0.38867188, -0.07128906,
        0.12109375,  0.203125  , -0.0135498 ,  0.12304688, -0.29101562,
       -0.01043701,  0.12988281,  0.21191406, -0.21484375,  0.12304688,
        0.265625  ,  0.20703125,  0.2109375 ,  0.43164062, -0.10302734,
        0.25976562, -0.04760742,  0.09619141,  0.15625   , -0.02368164,
       -0.28320312,  0.05249023,  0.23632812, -0.32226562,  0.09667969,
       -0.01086426, -0.13574219, -0.18261719, -0.22851562, -0.16894531,
        0.05053711, -0.11376953, -0.10009766, -0.22558594, -0.26171875,
       -0.24414062, -0.23828125,  0.13378906,  0.05761719,  0.28515625,
       -0.32421875,  0.03613281,  0.18847656, -0.09814453, -0.03857422,
        0.00640869, -0.18652344, -0.20800781,  0.28320312, -0.00686646,
        0.14355469, -0.14453125,  0.19628906,  0.18066406, -0.0050354 ,
       -0.32617188, -0.25390625, -0.11230469,  0.0703125 , -0.10

In [10]:
money.shape

(300,)

In [11]:
kind=wv['kind']

In [12]:
kind

array([ 0.13476562,  0.0456543 ,  0.05541992,  0.40429688, -0.20410156,
       -0.04296875,  0.19824219, -0.27539062,  0.00680542,  0.06445312,
        0.01550293, -0.10351562, -0.01574707, -0.25      , -0.11083984,
        0.14648438,  0.02624512,  0.20117188,  0.04956055, -0.17480469,
        0.02148438,  0.10498047,  0.00062943, -0.05029297,  0.16015625,
       -0.09423828, -0.05688477,  0.125     ,  0.10888672,  0.00201416,
       -0.18554688, -0.01434326,  0.09277344,  0.20214844,  0.01794434,
       -0.09814453,  0.07177734, -0.14355469,  0.06005859,  0.16699219,
        0.16699219, -0.06005859,  0.10351562, -0.03100586, -0.12255859,
        0.04199219, -0.02807617,  0.01574707,  0.04858398,  0.12988281,
       -0.01623535,  0.14941406, -0.08789062, -0.05688477,  0.17480469,
        0.06298828, -0.06225586, -0.12060547,  0.12695312, -0.14257812,
        0.03149414,  0.00221252, -0.03417969,  0.03198242, -0.06640625,
       -0.06982422,  0.05395508,  0.07275391, -0.08349609,  0.04

In [14]:
wv.most_similar('Badminton')

[('badminton', 0.682066023349762),
 ('Table_Tennis', 0.6493501663208008),
 ('shuttlers', 0.6312325596809387),
 ('Squash', 0.6216728091239929),
 ('Korfball', 0.5877218246459961),
 ('Junior_Squash', 0.5876492261886597),
 ('Indonesia_PBSI', 0.5870384573936462),
 ('Tennis', 0.5850102305412292),
 ('Table_Tennis_Association', 0.5841672420501709),
 ('Sepaktakraw', 0.5816634297370911)]

In [15]:
wv.most_similar('Business')

[('Busines', 0.6567192673683167),
 ('Buisness', 0.6348280310630798),
 ('Entrepreneurial', 0.592933177947998),
 ('Small_Business', 0.5881316661834717),
 ('Entrepreneurship', 0.5593594908714294),
 ('Businesss', 0.5565901398658752),
 ('business', 0.5466139316558838),
 ('Real_Estate', 0.5399389266967773),
 ('Retail', 0.5347363352775574),
 ('Busi_ness', 0.531885027885437)]

In [16]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [17]:
wv.similarity('sweet','Delicious')

np.float32(0.30222917)

In [19]:
print(wv.similarity('cricket','cricketers'))

0.8165746


In [26]:
cal=wv['Stupid']-wv['ashame']+wv['sad']

In [21]:
cal

array([ 0.5806885 , -0.13415527,  0.14526367,  0.02368164,  0.0604248 ,
       -0.16497803,  0.12890625,  0.06469727,  0.5966797 ,  0.18041992,
        0.00866699,  0.2998047 , -0.07193756,  0.43554688,  0.06445312,
       -0.1328125 , -0.00604248,  0.06713867, -0.32128906, -0.05322266,
        0.15808105,  0.12088013,  0.47094727,  0.12609863,  0.25195312,
        0.16894531,  0.03198242,  0.1895752 ,  0.37890625, -0.21484375,
       -0.6154785 , -0.32348633,  0.02612305, -0.22088623,  0.15771484,
       -0.03407288, -0.21875   ,  0.20898438,  0.09002686, -0.06005859,
        0.00683594,  0.3005371 ,  0.05273438,  0.01068115,  0.4729004 ,
       -0.01904297, -0.12756348,  0.30371094, -0.52685547, -0.1965332 ,
       -0.54785156, -0.09906006,  0.60058594,  0.16418457,  0.49902344,
        0.22454834, -0.2841797 , -0.3779297 ,  0.10107422,  0.1003418 ,
        0.00244141,  0.5131836 , -0.14343262, -0.00292969, -0.30078125,
       -0.4212036 , -0.02270508,  0.3071289 , -0.10229492,  0.10

In [27]:
wv.most_similar(cal)

[('Stupid', 0.726937472820282),
 ('sad', 0.5957369804382324),
 ('Sad', 0.5367304086685181),
 ('Saddest', 0.4998498558998108),
 ('Disgusting', 0.47412601113319397),
 ('Depressing', 0.4711233377456665),
 ('Pathetic', 0.4671991467475891),
 ('ironic', 0.4625714421272278),
 ('depressing', 0.4596063792705536),
 ('Unfunny', 0.45532914996147156)]